export const LOAD_MARKERS_SUCCESS = "LOAD_MARKERS_SUCCESS";
export const CREATE_MARKER = "CREATE_MARKER";
export const CREATE_MARKER_SUCCESS = "CREATE_MARKERS_SUCCESS";
export const UPDATE_MARKER_SUCCESS = "UPDATE_MARKERS_SUCCESS";
export const DELETE_MARKER_OPTIMISTIC = "DELETE_MARKER_OPTIMISTIC";